---
- rule: 'rpc.enable? OR !(''advanced.pruning.mode = "manual")'
  description: "RPC must be enabled for manual pruning."
- rule: '!(txindex?) OR ''advanced.pruning.mode = "disabled"'
  description: "Txindex not allowed on pruned nodes."
