import { VersionInfo } from '@start9labs/start-sdk'
import { rm } from 'fs/promises'

export const current = VersionInfo.of({
  version: '31.1:5',
  releaseNotes: {
    en_US: `Adds a Private Broadcast setting for pushing transactions out over Tor or I2P, fixes on-demand fetching of pruned blocks, and repairs the UTXO snapshot download.

Peer Settings now carries a Private Broadcast toggle. It is a Bitcoin Core 31 feature the package already understood but never offered anywhere in the interface. With it on, a transaction handed to your node through the sendrawtransaction RPC — how an external wallet that holds its own keys broadcasts through your node — is pushed over a few short-lived Tor or I2P connections opened just for it, rather than announced to the peers your node is already talking to. Those peers no longer learn that the transaction started with you, and two transactions of yours can no longer be tied together by the connection they arrived on. Transactions sent from Bitcoin Core's own wallet are unchanged, and the setting is off unless you turn it on.

It only helps if Tor or I2P actually works: I2P is enabled out of the box, while Tor requires the Tor service to be installed and running. Two other settings cannot be combined with it, because Bitcoin would refuse to start — connecting exclusively to a list of peers you choose, and an Onlynet that leaves out both Tor and I2P — so Peer Settings now tells you which one is in the way instead of saving a configuration the node cannot start with.

A pruned node keeps only recent blocks, so this package bundles a proxy that fetches any older block from the peer-to-peer network the moment something asks for it — that is what lets a Lightning node, Electrum server or block explorer work against a pruned node. The proxy was running, but the fetching itself was never switched on, so any request for a block older than your prune depth simply failed. LND, for one, could never finish building its channel graph. Those requests are now served as intended. The fetch is also cheaper and reaches further: a block is pulled from a few peers rather than all of them at once, and peers reachable only over I2P now count, where before they were tried and always failed. The proxy image is pinned to a fixed release instead of following a moving tag. Unpruned nodes are unaffected — they never run the proxy.

The "Download UTXO Snapshot (assumeutxo)" action has also been repaired. Every attempt failed the instant it started, reporting a missing file that had nothing to do with the address you entered — the program the action used to fetch the snapshot was no longer shipped with the service. Downloads now start as intended, and a URL that answers with an error page is reported as a failed download rather than saved as though it were a snapshot. The action is sturdier around it too: a transfer that stalls is resumed where it left off rather than restarted from zero, and abandoned only once it has genuinely stopped moving; the wait for the chain's headers to reach the snapshot height gives up after six hours instead of leaving the action on "Download in progress" until the service is restarted; a failure now tells you what went wrong instead of only that it failed; and the snapshot file — around 11 GB — is deleted once Bitcoin has absorbed it. The address field also states what it wants: a direct link to a .dat snapshot, which may be one you serve from your own machine over the LAN.`,
    es_ES: `Añade un ajuste de Transmisión privada para enviar transacciones a través de Tor o I2P, corrige la obtención bajo demanda de bloques podados y repara la descarga de la instantánea UTXO.

La Configuración de pares incorpora ahora un interruptor de Transmisión privada. Es una función de Bitcoin Core 31 que el paquete ya entendía, pero que nunca se ofreció en ninguna parte de la interfaz. Con ella activada, una transacción entregada a tu nodo mediante el RPC sendrawtransaction —la forma en que una billetera externa que custodia sus propias claves difunde a través de tu nodo— se envía por unas pocas conexiones Tor o I2P efímeras abiertas solo para ella, en lugar de anunciarse a los pares con los que tu nodo ya está hablando. Esos pares dejan de saber que la transacción partió de ti, y dos transacciones tuyas ya no pueden vincularse entre sí por la conexión por la que llegaron. Los envíos desde la propia billetera de Bitcoin Core no cambian, y el ajuste está desactivado salvo que tú lo actives.

Solo sirve si Tor o I2P funcionan de verdad: I2P viene activado de fábrica, mientras que Tor requiere que el servicio Tor esté instalado y en ejecución. Hay otros dos ajustes que no pueden combinarse con él, porque Bitcoin se negaría a arrancar —conectarse exclusivamente a una lista de pares que tú elijas, y un Onlynet que deje fuera tanto a Tor como a I2P—, así que la Configuración de pares te dice ahora cuál es el que estorba en lugar de guardar una configuración con la que el nodo no puede arrancar.

Un nodo podado solo conserva los bloques recientes, por lo que este paquete incluye un proxy que descarga cualquier bloque más antiguo de la red entre pares en cuanto algo lo solicita: eso es lo que permite que un nodo Lightning, un servidor Electrum o un explorador de bloques funcionen contra un nodo podado. El proxy estaba en marcha, pero esa descarga nunca llegó a activarse, así que cualquier petición de un bloque anterior a tu profundidad de poda fallaba sin más. LND, por ejemplo, nunca lograba terminar de construir su grafo de canales. Esas peticiones ya se atienden como corresponde. La descarga también es más económica y llega más lejos: un bloque se solicita a unos pocos pares en lugar de a todos a la vez, y los pares accesibles solo por I2P ya cuentan, cuando antes se intentaban y siempre fallaban. La imagen del proxy está fijada a una versión concreta en lugar de seguir una etiqueta móvil. Los nodos sin podar no se ven afectados: nunca ejecutan el proxy.

También se ha reparado la acción "Descargar instantánea UTXO (assumeutxo)". Todos los intentos fallaban nada más empezar, informando de un archivo inexistente que nada tenía que ver con la dirección introducida: el programa que la acción usaba para descargar la instantánea ya no venía incluido en el servicio. Las descargas ahora arrancan como corresponde, y una URL que responde con una página de error se notifica como descarga fallida en lugar de guardarse como si fuera una instantánea. La acción también es más robusta a su alrededor: una transferencia que se atasca se reanuda donde quedó en lugar de empezar de cero, y solo se abandona cuando de verdad ha dejado de avanzar; la espera a que las cabeceras de la cadena alcancen la altura de la instantánea se rinde ahora a las seis horas en lugar de dejar la acción atascada en "Descarga en progreso" hasta reiniciar el servicio; un fallo ahora te dice qué salió mal y no solo que falló; y el archivo de la instantánea —unos 11 GB— se elimina en cuanto Bitcoin lo ha absorbido. El campo de la dirección indica además lo que espera: un enlace directo a un archivo .dat, que puede ser uno que sirvas desde tu propia máquina por la LAN.`,
    de_DE: `Ergänzt die Einstellung Privater Broadcast, um Transaktionen über Tor oder I2P hinauszuschicken, behebt das bedarfsgesteuerte Nachladen beschnittener Blöcke und repariert den Download des UTXO-Snapshots.

Die Peer-Einstellungen enthalten jetzt einen Schalter für Privater Broadcast. Es ist eine Funktion von Bitcoin Core 31, die das Paket bereits verstand, aber nirgends in der Oberfläche anbot. Ist sie aktiv, wird eine Transaktion, die über den sendrawtransaction-RPC an deinen Knoten übergeben wird — so sendet eine externe Wallet, die ihre Schlüssel selbst verwahrt, über deinen Knoten —, über einige eigens dafür geöffnete, kurzlebige Tor- oder I2P-Verbindungen hinausgeschickt, statt den Peers angekündigt zu werden, mit denen dein Knoten ohnehin spricht. Diese Peers erfahren nicht mehr, dass die Transaktion von dir stammt, und zwei deiner Transaktionen lassen sich nicht mehr über die Verbindung verknüpfen, auf der sie eintrafen. Sendungen aus Bitcoin Cores eigener Wallet bleiben unverändert, und die Einstellung ist aus, solange du sie nicht einschaltest.

Sie nützt nur, wenn Tor oder I2P tatsächlich funktioniert: I2P ist ab Werk aktiviert, Tor setzt den installierten und laufenden Tor-Dienst voraus. Zwei weitere Einstellungen lassen sich nicht damit kombinieren, weil Bitcoin den Start verweigern würde — ausschließlich zu einer selbst gewählten Peer-Liste zu verbinden und ein Onlynet, das sowohl Tor als auch I2P auslässt —, deshalb nennen die Peer-Einstellungen jetzt die störende Einstellung, statt eine Konfiguration zu speichern, mit der der Knoten nicht startet.

Ein beschnittener Knoten behält nur die jüngsten Blöcke, deshalb bringt dieses Paket einen Proxy mit, der jeden älteren Block in dem Moment aus dem Peer-to-Peer-Netz nachlädt, in dem etwas ihn anfordert — genau das lässt einen Lightning-Knoten, einen Electrum-Server oder einen Block-Explorer mit einem beschnittenen Knoten arbeiten. Der Proxy lief zwar, das Nachladen selbst war aber nie eingeschaltet, sodass jede Anfrage nach einem Block jenseits deiner Prune-Tiefe schlicht fehlschlug. LND etwa konnte seinen Kanalgraphen nie fertig aufbauen. Diese Anfragen werden jetzt wie vorgesehen bedient. Das Nachladen ist außerdem sparsamer und reicht weiter: Ein Block wird von einigen wenigen Gegenstellen geholt statt von allen gleichzeitig, und Peers, die nur über I2P erreichbar sind, zählen jetzt mit — zuvor wurden sie versucht und schlugen stets fehl. Das Proxy-Image ist zudem auf eine feste Version festgelegt, statt einem beweglichen Tag zu folgen. Unbeschnittene Knoten sind nicht betroffen — sie starten den Proxy nie.

Außerdem wurde die Aktion „UTXO-Snapshot herunterladen (assumeutxo)" repariert. Jeder Versuch schlug sofort fehl und meldete eine fehlende Datei, die nichts mit der eingegebenen Adresse zu tun hatte — das Programm, mit dem die Aktion den Snapshot holte, wurde nicht mehr mit dem Dienst ausgeliefert. Downloads starten jetzt wie vorgesehen, und eine URL, die mit einer Fehlerseite antwortet, wird als fehlgeschlagener Download gemeldet, statt als Snapshot gespeichert zu werden. Auch drumherum ist die Aktion robuster: Eine ins Stocken geratene Übertragung wird an der Abbruchstelle fortgesetzt statt bei null neu begonnen und erst aufgegeben, wenn sie tatsächlich nicht mehr vorankommt; das Warten darauf, dass die Header der Kette die Snapshot-Höhe erreichen, gibt jetzt nach sechs Stunden auf, statt die Aktion bis zum Neustart des Dienstes bei „Download läuft" hängen zu lassen; ein Fehlschlag nennt jetzt die Ursache statt nur zu melden, dass er fehlschlug; und die Snapshot-Datei — rund 11 GB — wird gelöscht, sobald Bitcoin sie aufgenommen hat. Das Adressfeld sagt außerdem, was es erwartet: einen direkten Link auf eine .dat-Snapshot-Datei, die auch von deinem eigenen Rechner im LAN stammen kann.`,
    pl_PL: `Dodaje ustawienie Prywatne rozgłaszanie, które wysyła transakcje przez Tora lub I2P, naprawia pobieranie na żądanie bloków usuniętych przez przycinanie oraz pobieranie migawki UTXO.

Ustawienia peerów mają teraz przełącznik Prywatne rozgłaszanie. To funkcja Bitcoin Core 31, którą pakiet już rozumiał, ale której nigdzie nie udostępniał w interfejsie. Gdy jest włączona, transakcja przekazana twojemu węzłowi przez RPC sendrawtransaction — tak rozgłasza przez twój węzeł zewnętrzny portfel przechowujący własne klucze — jest wypychana kilkoma krótkotrwałymi połączeniami Tor lub I2P otwartymi wyłącznie dla niej, zamiast być ogłaszana peerom, z którymi twój węzeł i tak rozmawia. Ci peerzy nie dowiadują się już, że transakcja wyszła od ciebie, a dwóch twoich transakcji nie da się powiązać po połączeniu, którym dotarły. Wysyłki z własnego portfela Bitcoin Core pozostają bez zmian, a ustawienie jest wyłączone, dopóki go nie włączysz.

Pomaga tylko wtedy, gdy Tor lub I2P faktycznie działa: I2P jest włączone od razu, natomiast Tor wymaga zainstalowanej i działającej usługi Tor. Dwóch innych ustawień nie da się z nim połączyć, bo Bitcoin odmówiłby uruchomienia — łączenia się wyłącznie z wybraną przez ciebie listą peerów oraz Onlynet pomijającego zarówno Tora, jak i I2P — więc Ustawienia peerów wskazują teraz, które z nich przeszkadza, zamiast zapisywać konfigurację, z którą węzeł nie wystartuje.

Węzeł z włączonym przycinaniem przechowuje tylko najnowsze bloki, dlatego pakiet zawiera proxy, które pobiera każdy starszy blok z sieci peer-to-peer w chwili, gdy coś go zażąda — to właśnie pozwala węzłowi Lightning, serwerowi Electrum czy eksploratorowi bloków działać na przyciętym węźle. Proxy działało, ale samo pobieranie nigdy nie zostało włączone, więc każde żądanie bloku starszego niż twoja głębokość przycinania po prostu kończyło się błędem. LND na przykład nigdy nie potrafił dokończyć budowy swojego grafu kanałów. Te żądania są już obsługiwane zgodnie z założeniem. Samo pobieranie jest też tańsze i sięga dalej: blok jest ściągany od kilku węzłów zamiast od wszystkich naraz, a węzły osiągalne wyłącznie przez I2P wreszcie się liczą — wcześniej były próbowane i zawsze zawodziły. Obraz proxy jest też przypięty do konkretnego wydania, zamiast podążać za ruchomym tagiem. Węzłów bez przycinania to nie dotyczy — nigdy nie uruchamiają proxy.

Naprawiono również akcję „Pobierz migawkę UTXO (assumeutxo)". Każda próba kończyła się błędem natychmiast po uruchomieniu, zgłaszając brakujący plik niemający nic wspólnego z podanym adresem — program, którym akcja pobierała migawkę, przestał być dostarczany razem z usługą. Pobieranie zaczyna się teraz zgodnie z założeniem, a adres URL zwracający stronę błędu jest zgłaszany jako nieudane pobranie, zamiast zostać zapisany tak, jakby był migawką. Sama akcja jest też odporniejsza: przerwane pobieranie jest wznawiane od miejsca zatrzymania, a nie zaczynane od zera, i porzucane dopiero wtedy, gdy naprawdę przestanie postępować; oczekiwanie, aż nagłówki łańcucha osiągną wysokość migawki, poddaje się teraz po sześciu godzinach, zamiast blokować akcję na „Pobieranie w toku" aż do restartu usługi; niepowodzenie podaje teraz przyczynę, a nie tylko sam fakt błędu; a plik migawki — około 11 GB — jest usuwany, gdy tylko Bitcoin go wchłonie. Pole adresu mówi ponadto, czego oczekuje: bezpośredniego odnośnika do pliku .dat, który może pochodzić z twojego własnego komputera w sieci lokalnej.`,
    fr_FR: `Ajoute un réglage Diffusion privée pour envoyer les transactions via Tor ou I2P, corrige la récupération à la demande des blocs élagués et répare le téléchargement de l'instantané UTXO.

Les Paramètres des pairs comportent désormais un interrupteur Diffusion privée. C'est une fonctionnalité de Bitcoin Core 31 que le paquet comprenait déjà mais n'offrait nulle part dans l'interface. Lorsqu'elle est active, une transaction remise à votre nœud via le RPC sendrawtransaction — la façon dont un portefeuille externe qui conserve ses propres clés diffuse à travers votre nœud — est poussée sur quelques connexions Tor ou I2P éphémères ouvertes rien que pour elle, au lieu d'être annoncée aux pairs auxquels votre nœud parle déjà. Ces pairs n'apprennent plus que la transaction vient de vous, et deux de vos transactions ne peuvent plus être reliées par la connexion sur laquelle elles sont arrivées. Les envois depuis le portefeuille de Bitcoin Core lui-même ne changent pas, et le réglage reste désactivé tant que vous ne l'activez pas.

Cela ne sert que si Tor ou I2P fonctionne réellement : I2P est activé d'origine, tandis que Tor exige que le service Tor soit installé et en cours d'exécution. Deux autres réglages ne peuvent pas être combinés avec lui, car Bitcoin refuserait de démarrer — se connecter exclusivement à une liste de pairs que vous choisissez, et un Onlynet qui laisse de côté à la fois Tor et I2P — ; les Paramètres des pairs indiquent donc maintenant lequel fait obstacle au lieu d'enregistrer une configuration avec laquelle le nœud ne peut pas démarrer.

Un nœud élagué ne conserve que les blocs récents ; ce paquet embarque donc un proxy qui récupère n'importe quel bloc plus ancien sur le réseau pair-à-pair dès que quelque chose le demande — c'est ce qui permet à un nœud Lightning, un serveur Electrum ou un explorateur de blocs de fonctionner avec un nœud élagué. Le proxy tournait, mais cette récupération n'a jamais été activée : toute demande d'un bloc antérieur à votre profondeur d'élagage échouait purement et simplement. LND, par exemple, ne parvenait jamais à terminer la construction de son graphe de canaux. Ces demandes sont désormais servies comme prévu. La récupération est aussi moins coûteuse et porte plus loin : un bloc est demandé à quelques pairs plutôt qu'à tous à la fois, et les pairs joignables uniquement via I2P comptent désormais, alors qu'ils étaient auparavant essayés puis échouaient systématiquement. L'image du proxy est en outre figée sur une version précise au lieu de suivre une étiquette mouvante. Les nœuds non élagués ne sont pas concernés : ils n'exécutent jamais le proxy.

L'action « Télécharger l'instantané UTXO (assumeutxo) » a également été réparée. Chaque tentative échouait dès son lancement en signalant un fichier introuvable sans rapport avec l'adresse saisie : le programme que l'action utilisait pour récupérer l'instantané n'était plus livré avec le service. Les téléchargements démarrent désormais comme prévu, et une URL qui répond par une page d'erreur est signalée comme un téléchargement échoué au lieu d'être enregistrée comme s'il s'agissait d'un instantané. L'action est aussi plus robuste autour : un transfert qui cale reprend là où il s'était arrêté au lieu de repartir de zéro, et n'est abandonné qu'une fois réellement à l'arrêt ; l'attente que les en-têtes de la chaîne atteignent la hauteur de l'instantané renonce désormais au bout de six heures au lieu de laisser l'action bloquée sur « Téléchargement en cours » jusqu'au redémarrage du service ; un échec indique désormais ce qui a mal tourné et non plus seulement qu'il a échoué ; et le fichier d'instantané — environ 11 Go — est supprimé une fois que Bitcoin l'a absorbé. Le champ d'adresse précise en outre ce qu'il attend : un lien direct vers un fichier .dat, qui peut être servi depuis votre propre machine sur le réseau local.`,
  },
  migrations: {
    up: async ({ effects }) => {},
    down: async ({ effects }) => {
      // v31 changed CURRENT_FEES_FILE_VERSION (149900 → 309900) and the
      // fee estimator bucket size; ≤30 hard-fails on a v31-written file.
      await rm('/media/startos/volumes/main/fee_estimates.dat', {
        force: true,
      }).catch(console.error)
    },
  },
})
  .satisfies('30.3:5')
  .satisfies('29.4:5')
  .satisfies('28.4:18')
